# Generated by Django 4.2.7 on 2024-02-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_appointment_age_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
    ]
