# Generated by Django 4.2.7 on 2024-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_remove_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'adminlogin',
            },
        ),
    ]
