# Generated by Django 4.2.7 on 2024-02-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_adminsign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminsign',
            table='adminsign',
        ),
    ]
