# Generated by Django 4.2.7 on 2024-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_adminsign_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='issues',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
