# Generated by Django 4.2.7 on 2024-03-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_appointment_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminsign',
        ),
    ]
