# Generated by Django 4.2.7 on 2024-04-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_docters'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='docters',
            table='docters',
        ),
    ]
